### ISSUE TITLE
Composer Package Location Error

### ISSUE THREAD

**Issue by Rican7** [vim-php/phpctags#33]
Since this repo has been moved from the original location (https://github.com/techlivezheng/phpctags) to its new location under "vim-php", it gets a redirect courtesy of GitHub.

Unfortunately, GitHub only does the redirection on the web stack and not for the API layer, so right now the GitHub API is returning a 404 when composer tries to grab the "zipball" (when using composer's "prefer-dist" option) during the composer installation process.

Either way, the packagist entry needs to be updated to point to the new location.

**Comment by gianarb** [comment]
Hi! Sorry I don't understand why 
https://packagist.org/packages/techlivezheng/phpctags
not works?

**Comment by Rican7** [comment]
@gianarb that's the Packagist link, which does work. Composer properly looks up the package, but the package still has the old GitHub repo URI in its location meta. It needs to be updated/refreshed for the new GH repo location. Maybe a quick Packagist force-reload would work?

**Comment by gianarb** [comment]
Oh ok! I cannot make this stuff.. :) No permission..
ping @techlivezheng about it! :) 
Thanks

**Comment by gianarb** [comment]
PING @weynhamz

**Comment by InFog** [comment]
I would like to fix it. Who can give me access? @weynhamz ?

**Comment by InFog** [comment]
I created a new package in packagist: https://github.com/vim-php/phpctags

Closing this issue now.
