### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by dsdeiz** [vim-php/phpctags#34]
Hey all,

I'm giving `phpctags` a try for the first time. I'm not entirely sure if I am doing it right though. I generated it like this where I am in the current directory of a project `phpctags -R --verbose --debug --memory=-1 .` although was getting this error:
```
PHP Notice:  Undefined variable: filename in phar:///usr/local/bin/phpctags/PHPCtags.class.php on line 424

Notice: Undefined variable: filename in phar:///usr/local/bin/phpctags/PHPCtags.class.php on line 424
PHPParser: No File specified. -
```

Any ideas?

**Comment by INTPnerd** [comment]
I'm still not sure how to use this. It doesn't seem to be creating any tags file. What file should it create if I run `phpctags -R .` ?

**Comment by gianarb** [comment]
Reference #23 

@dsdeiz have you try this command with actual version?

**Comment by dsdeiz** [comment]
Sorry, I can't remember.

I guess I encountered an error during that time since I got an error on my first comment. I might've been using the original repo during that time.

I'm still using @mr-russ phpctags version and haven't changed it since then. Would be nice if the original repo is updated.

**Comment by gianarb** [comment]
@dsdeiz we are working for this! :) 
Thanks for your feedback, I close this issue
