### ISSUE TITLE
phpctags does not work with namespaces

### ISSUE THREAD

**Issue by Martiusweb** [vim-php/phpctags#4]
When I try phpctags on a file with a namespace statement at the begining of the file, I get an empty list of tags.

Tested on symfony2 files and with a simple test file :

```
class Foo {
}
```

returns

```
Foo /tmp/t.php  /^class Foo {$/;"   c   line:5
```

 whereas

```
namespace Bar;

class Foo {
}
```

returns nothing

**Comment by McUsr** [comment]
I have problems with Doxygen comments after namespace, or any comment actually.
That is comments starting like this : /** and comments starting like this: /* right below the namespace declaration.
