### ISSUE TITLE
Build phpctags executable on post-install or post-update

### ISSUE THREAD

**Issue by marcinant** [vim-php/phpctags#53]
As in topic.

If executable binary is not a part of distribution then it could be great to add build script with 'make' command to composer 'post-install-cmd' or/and 'post-update-cmd'.

**Comment by gianarb** [comment]
Sorry but I don't understand :)

**Comment by marcinant** [comment]
In `composer.json` there is an information about binary.
`"bin": ["phpctags"]`
However this binary is not a part of repository and user has to run make.

Unfortunately 'post-install-cmd' scripts are not executed for dependencies. So, the only solution is to precompile binary and make it a part of distribution.

**Comment by gianarb** [comment]
There are a lot of problems into the build flow :)
In this moment the code base is ready for another version 0.6.0.. :) I'm
thinking a good flow before tag it!

2015-05-14 11:39 GMT+02:00 Martin <notifications@github.com>:

> In composer.json there is an information about binary.
> "bin": ["phpctags"]
> However this binary is not a part of repository and user has to run make.
>
> Unfortunately 'post-install-cmd' scripts are not executed for
> dependencies. So, the only solution is to precompile binary and make it a
> part of distribution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vim-php/phpctags/issues/53#issuecomment-101985493>.
>



-- 
Gianluca Arbezzano
www.gianarb.it

**Comment by gianarb** [comment]
@marcinant master is out of date..
We are working into the develop and in now che composer.json is correctly.. We use bin/phpctags how bin entry point of application an this is into the repository without build process :)
