### ISSUE TITLE
Multiple exclude options are ignored

### ISSUE THREAD

**Issue by lukepass** [vim-php/phpctags#58]
Hello,
it seems that when specifying multiple `--exclude` options, only the last one is correctly applied. On standard ctags I can specify multiple options: [Exuberant ctags exclude directories](http://stackoverflow.com/questions/25819649/exuberant-ctags-exclude-directories)

Thanks.

**Comment by lukepass** [comment]
I added a PR for this fix: https://github.com/vim-php/phpctags/pull/60

**Comment by lukepass** [comment]
I added tests in another PR, sorry but I didn't know how to put code and tests on the same PR: https://github.com/vim-php/phpctags/pull/61

**Comment by gianarb** [comment]
Currently merged into master
