### ISSUE TITLE
php-parser compatibility.

### ISSUE THREAD

**Issue by musou1500** [vim-php/phpctags#62]
php-parser uses namespace since version 1.0.
So, error occures on build.
```
PHP Fatal error:  Class 'PHPParser_Parser' not found in /path/to/phpctags/PHPCtags.class.php on line 31
```

please sea this document.
[https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-1.0.md#move-to-namespaced-names](https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-1.0.md#move-to-namespaced-names)

**Comment by musou1500** [comment]
I create a pull-request.
#63

**Comment by gianarb** [comment]
Resolved 4835548
Thanks a lot

**Comment by fntlnz** [comment]
@gianarb can be closed?

**Comment by gianarb** [comment]
Yes thanks!
