### ISSUE TITLE
Jump to method from another class.

### ISSUE THREAD

**Issue by FernandoBasso** [vim-php/phpctags#75]
If I am on the controller class, inside a method which invokes a method from the mapper class like this:

``` php
class FooController {
    /**
     * @var FooMapper
     */
    private $_mapper;

    public function __construct() {
        $this-_mapper = new FooMapper();
    }

    public function destroy($id) {
        //             ↑ jumps to this place...

        // some code...


        $this->_mapper->destroy($id);
        //                 ↑ Ctrl+[
    }
}
```

Where ↑ is the position of the cursor, if I do `Ctrl+[` I jump to the `destroy` method on the controller itself, and not to the `destroy` method on the Mapper class.

Is that how it is supposed to work? Perhaps I am missing some configs?

**Comment by InFog** [comment]
I believe this is out of the context for the tags generator. Maybe you are using some other plugin to navigate to the definition of the method?

I'm closing this one for now.
