### ISSUE TITLE
Is it possible to generate tags for whole project

### ISSUE THREAD

**Issue by alexdrupal** [vim-php/phpctags#79]
Hello

Now i'm using ctags -R ..... is it possible with phpctags?

**Comment by jespinal** [comment]
Hello, @alexdrupal : 

Yes, it is possible. After cloning the repo and building the phpctags (`make all`, which places the generated files under the build/ directory), I created a symlink under some directory in my PATH and was able to create a whole project PHP tags file.

`$ cd path_to_my_project_dir/`
`$ phpctags --memory=-1 -R`

Regards,

**Comment by InFog** [comment]
I'm closing this one, as the answer is already given.

**Comment by jay-knight** [comment]
Maybe put this in the README file?

**Comment by InFog** [comment]
Good idea, @jay-knight.

It is done here: https://github.com/vim-php/phpctags/commit/3d7acda51a467bcae99d6e2b78f57178b1f106c2
