### ISSUE TITLE
vim-php.com site down?

### ISSUE THREAD

**Issue by mlopezgva** [vim-php/phpctags#83]
I was trying to get the phar using `http://vim-php.com/phpctags/install/phpctags.phar` but it can't resolve the hostname... Any alternatives? Thank you.

**Comment by jmramos02** [comment]
experiencing this. looks like it

**Comment by jmramos02** [comment]
Looks like we need to build from source

**Comment by Mte90** [comment]
Confirmed the issue and also the new release is not available, but can be loaded in the release of github.

**Comment by mlopezgva** [comment]
I downloaded the source 0.7.0, but when I `make` it, it shows version 0.6.1?

**Comment by Mte90** [comment]
maybe they released a new version but didn't bump the version

**Comment by mlopezgva** [comment]
Well, I just updated it (apparently to 0.6.1...), I hope it still works as expected. :-)

**Comment by InFog** [comment]
http://vim-php.com/phpctags/install/phpctags.phar is fixed now and on 0.8.0

**Comment by mlopezgva** [comment]
It seems like it's not working...

![image](https://user-images.githubusercontent.com/996070/115967580-b5fb6a00-a533-11eb-8c16-aa461c113f55.png)

_"vim-php.com" not found_

**Comment by InFog** [comment]
It seems to be down. I'm not sure who can help.

We can still update the documentation to point to github instead.
