### ISSUE TITLE
Not working with composer and vendor folder

### ISSUE THREAD

**Issue by more-pepsi** [vim-php/phpctags#87]
Making a composer project with dependencies and then creating tags for my app

phpctags -R ./app
an for the dependencies
phpctags -R --append ./vendor

only creates tags for  ./app

Nor does, phpctags -rR ./vendor. this creates no file. However phpctags ./vendor/somepackage does produce them for that package.

php 8.1

**Comment by more-pepsi** [comment]
I was able to overcome this by settings the --memory=-1

also

I was running composer inside laravel sail which is a docker container so the tags produced the project outpput

**Comment by InFog** [comment]
Thanks for the update @more-pepsi.
